name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  pr:  # id of input
    description: 'ID of Pull Request'
    required: true
  sessionToken:
    description: 'Your ChatGPT session token.'
    required: true
outputs:
  comment:
    description: 'The comment from chatgpt.'
runs:
  using: 'node16'
  main: 'dist/index.js'
