name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  number:  # id of input
    description: 'ID of Pull Request or Issue'
    required: true
  sessionToken:
    description: 'Your ChatGPT session token.'
    required: true
  mode:
    description: 'Mode'
    required: true
    default: 'pr'
outputs:
  comment:
    description: 'The comment from chatgpt.'
runs:
  using: 'node16'
  main: 'dist/index.js'
