name: 'ChatGPT Integration'
description: 'This action integrates ChatGPT into your CI.'
inputs:
  number:
    description: 'ID of Pull Request or Issue'
    required: true
  sessionToken:
    description: 'Your ChatGPT session token.'
    required: true
  mode:
    description: 'Mode'
    required: true
    default: 'pr'
outputs:
  comment:
    description: 'The comment from chatgpt.'
runs:
  using: 'node16'
  main: 'dist/index.js'
